### ISSUE TITLE
Error with Internet Explorer 11

### ISSUE THREAD

**Issue by Hypocrite** [zhaber/angular-js-bootstrap-datetimepicker#105]
I am getting the following error with Internet Explorer 11:
```
ReferenceError: 'XPathResult' is undefined
at Anonymous function (http://192.168.99.11/bower_components/angular-ui-bootstrap-datetimepicker/datetimepicker.js:185:13)
at Scope.prototype.$digest (http://192.168.99.11/bower_components/angular/angular.js:17073:23)
at Scope.prototype.$apply (http://192.168.99.11/bower_components/angular/angular.js:17337:13)
at done (http://192.168.99.11/bower_components/angular/angular.js:11572:36)
at completeRequest (http://192.168.99.11/bower_components/angular/angular.js:11778:7)
at requestLoaded (http://192.168.99.11/bower_components/angular/angular.js:11711:9)
ReferenceError: 'XPathResult' is undefined
at Anonymous function (http://192.168.99.11/bower_components/angular-ui-bootstrap-datetimepicker/datetimepicker.js:185:13)
at Scope.prototype.$digest (http://192.168.99.11/bower_components/angular/angular.js:17073:23)
at Scope.prototype.$apply (http://192.168.99.11/bower_components/angular/angular.js:17337:13)
at done (http://192.168.99.11/bower_components/angular/angular.js:11572:36)
at completeRequest (http://192.168.99.11/bower_components/angular/angular.js:11778:7)
at requestLoaded (http://192.168.99.11/bower_components/angular/angular.js:11711:9)
```

This results in the timepicker to not show any time by default.

![screenshot 2016-04-29 09 57 08](https://cloud.githubusercontent.com/assets/1395541/14909868/dde9d338-0df0-11e6-8909-89d8fcbe9f9c.png)

**Comment by Robin-Hoodie** [comment]
This was fixed in PR #102
