### ISSUE TITLE
date-format cannot be set by code

### ISSUE THREAD

**Issue by rosieks** [zhaber/angular-js-bootstrap-datetimepicker#84]
I'm just trying to set `date-format` from code so I have something like this:

`<datetimepicker ng-model="ride.departure" show-meridian="false" date-format="{{vm.dateFormat}}" />`

Unfortunately in such case I receive the following error:

    Error: [$parse:syntax] Syntax Error: Token '{' invalid key at column 2 of the expression  [{{vm.dateFormat}}] starting at [{vm.dateFormat}}].
    http://errors.angularjs.org/1.4.8/$parse/syntax?p0=%7B&p1=invalid%20key&p2=2&p3=%7B%7Bvm.dateFormat%7D%7D&p4=%7Bvm.dateFormat%7D%7D
        at http://localhost:3000/bower_components/angular/angular.js:68:12
        at Object.AST.throwError (http://localhost:3000/bower_components/angular/angular.js:13100:11)
        at Object.AST.object (http://localhost:3000/bower_components/angular/angular.js:13087:16)
        at Object.AST.primary (http://localhost:3000/bower_components/angular/angular.js:12995:22)
        at Object.AST.unary (http://localhost:3000/bower_components/angular/angular.js:12983:19)
        at Object.AST.multiplicative (http://localhost:3000/bower_components/angular/angular.js:12970:21)
        at Object.AST.additive (http://localhost:3000/bower_components/angular/angular.js:12961:21)
        at Object.AST.relational (http://localhost:3000/bower_components/angular/angular.js:12952:21)
        at Object.AST.equality (http://localhost:3000/bower_components/angular/angular.js:12943:21)
        at Object.AST.logicalAND (http://localhost:3000/bower_components/angular/angular.js:12935:21) <div ng-show="inEditMode()" ng-transclude="">

It also fails if I change code in demo from `date-format="yyyy-MMM-dd"` to `date-format="{{'yyyy-MMM-dd'}}"`

**Comment by zhaber** [comment]
date-format is a string literal field. It's compatible with the underlying datepicker directive. See https://angular-ui.github.io/bootstrap/

**Comment by rosieks** [comment]
That's true, but it should be able to use interpolation to have some computed format like it's in datepicker directive.
Below is sample from Angular UI Bootstrap site:

```<input type="text" class="form-control" uib-datepicker-popup="{{format}}" ng-model="dt" is-open="popup1.opened" min-date="minDate" max-date="maxDate" datepicker-options="dateOptions" date-disabled="disabled(date, mode)" ng-required="true" close-text="Close" alt-input-formats="altInputFormats" />```

As you see there is `uib-datepicker-popup="{{format}}"` that let me compute format.

**Comment by zhaber** [comment]
Added support for interpolation in the last commit https://github.com/zhaber/angular-js-bootstrap-datetimepicker/commit/9120d012df09f7322dd3e0a370ecd65229d14566
