### ISSUE TITLE
Cannot read property '$removeControl' of undefined 

### ISSUE THREAD

**Issue by terracott** [zhaber/angular-js-bootstrap-datetimepicker#94]
I catch this error with the following environment:
``` javascript
{ 
    "angular": "1.5.0",
    "angular-bootstrap": "1.2.4",
    "angular-ui-bootstrap-datetimepicker": ">=0.14.3"
}
```

In 0.14.0 version I don't see it.

```
angular.js:13236 TypeError: Cannot read property '$removeControl' of undefined
    at link (http://localhost:3000/bower_components/angular-ui-bootstrap-datetimepicker/datetimepicker.js:232:19)
    at invokeLinkFn (http://localhost:3000/bower_components/angular/angular.js:9492:9)
    at nodeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8978:11)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8226:13)
    at nodeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8973:24)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8226:13)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8229:13)
    at publicLinkFn (http://localhost:3000/bower_components/angular/angular.js:8106:30)
    at http://localhost:3000/bower_components/angular/angular.js:1696:27
    at Scope.$eval (http://localhost:3000/bower_components/angular/angular.js:16820:28) <ng-form name="datetimepickerForm" isolate-form="" class="ng-pristine ng-valid">
```

**Comment by zhaber** [comment]
it should be fixed in the latest version of the directive https://github.com/zhaber/angular-js-bootstrap-datetimepicker/blob/master/datetimepicker.js

**Comment by terracott** [comment]
thnx, problem is fixed
